### ISSUE TITLE
DirectBuffer Cleaner method issue in JDK > 1.9

### ISSUE THREAD

**Issue by jblozano17** [hyee/OpenCSV#7]
When using OpenCSV with a JDK > 1.9 the following error appears on execution:

java.lang.NoSuchMethodError: 'sun.misc.Cleaner sun.nio.ch.DirectBuffer.cleaner()'
	at com.opencsv.FileBuffer.close(FileBuffer.java:161)
	at com.opencsv.CSVWriter.close(CSVWriter.java:382)
	at com.opencsv.CSVWriter.writeAll(CSVWriter.java:281)
	at com.opencsv.CSVWriter.writeAll(CSVWriter.java:244)

A similar issue can be found here https://github.com/apache/hadoop/commit/5d084d7eca32cfa647a78ff6ed3c378659f5b186

**Comment by tooptoop4** [comment]
@hyee @jblozano17 has there been new release with this fix or pom.xml available to self-build?
